*WELL  'Wildcat'
*PRODUCER 'Wildcat'
*OPERATE *MIN *BHP 50.0 *CONT
*GEOMETRY *K 0.0762 0.3700 1.0000 0.0000 ** rad geofac wfrac skin
*PERF *GEOA 'Wildcat'
16    36     1    FR    1.0    OPEN    FLOW-TO       'SURFACE' REFLAYER ** UBA ff Status Connection
16    36     1    MT    1.0    OPEN    FLOW-TO    ** 'SURFACE' REFLAYER
16    36     2    FR    1.0    OPEN    FLOW-TO    1
16    36     2    MT    1.0    OPEN    FLOW-TO    1
16    36     3    FR    1.0    OPEN    FLOW-TO    2
16    36     3    MT    1.0    OPEN    FLOW-TO    2
16    36     4    FR    1.0    OPEN    FLOW-TO    3
16    36     4    MT    1.0    OPEN    FLOW-TO    3
16    36     5    FR    1.0    OPEN    FLOW-TO    4
16    36     5    MT    1.0    OPEN    FLOW-TO    4
16    36     6    FR    1.0    OPEN    FLOW-TO    5
16    36     6    MT    1.0    OPEN    FLOW-TO    5
16    36     7    FR    1.0    OPEN    FLOW-TO    6
16    36     7    MT    1.0    OPEN    FLOW-TO    6
16    36     8    FR    1.0    OPEN    FLOW-TO    7
16    36     8    MT    1.0    OPEN    FLOW-TO    7
16    36     9    FR    1.0    OPEN    FLOW-TO    8
16    36     9    MT    1.0    OPEN    FLOW-TO    8
16    36    10    FR    1.0    OPEN    FLOW-TO    9
16    36    10    MT    1.0    OPEN    FLOW-TO    9
16    36    11    FR    1.0    OPEN    FLOW-TO    10
16    36    11    MT    1.0    OPEN    FLOW-TO    10
16    36    12    FR    1.0    OPEN    FLOW-TO    11
16    36    12    MT    1.0    OPEN    FLOW-TO    11
16    36    13    FR    1.0    OPEN    FLOW-TO    12
16    36    13    MT    1.0    OPEN    FLOW-TO    12
16    36    14    FR    1.0    OPEN    FLOW-TO    13
16    36    14    MT    1.0    OPEN    FLOW-TO    13
16    36    15    FR    1.0    OPEN    FLOW-TO    14
16    36    15    MT    1.0    OPEN    FLOW-TO    14
16    36    16    FR    1.0    OPEN    FLOW-TO    15
16    36    16    MT    1.0    OPEN    FLOW-TO    15
16    36    17    FR    1.0    OPEN    FLOW-TO    16
16    36    17    MT    1.0    OPEN    FLOW-TO    16
16    36    18    FR    1.0    OPEN    FLOW-TO    17
16    36    18    MT    1.0    OPEN    FLOW-TO    17
16    36    19    FR    1.0    OPEN    FLOW-TO    18
16    36    19    MT    1.0    OPEN    FLOW-TO    18
16    36    20    FR    1.0    OPEN    FLOW-TO    19
16    36    20    MT    1.0    OPEN    FLOW-TO    19
16    36    21    FR    1.0    OPEN    FLOW-TO    20
16    36    21    MT    1.0    OPEN    FLOW-TO    20
16    36    22    FR    1.0    OPEN    FLOW-TO    21
16    36    22    MT    1.0    OPEN    FLOW-TO    21
16    36    23    FR    1.0    OPEN    FLOW-TO    22
16    36    23    MT    1.0    OPEN    FLOW-TO    22
16    36    24    FR    1.0    OPEN    FLOW-TO    23
16    36    24    MT    1.0    OPEN    FLOW-TO    23
16    36    25    FR    1.0    OPEN    FLOW-TO    24
16    36    25    MT    1.0    OPEN    FLOW-TO    24
16    36    26    FR    1.0    OPEN    FLOW-TO    25
16    36    26    MT    1.0    OPEN    FLOW-TO    25
16    36    27    FR    1.0    OPEN    FLOW-TO    26
16    36    27    MT    1.0    OPEN    FLOW-TO    26
16    36    28    FR    1.0    OPEN    FLOW-TO    27
16    36    28    MT    1.0    OPEN    FLOW-TO    27
16    36    29    FR    1.0    OPEN    FLOW-TO    28
16    36    29    MT    1.0    OPEN    FLOW-TO    28
SHUTIN 'Wildcat'